<option value="NG">Nigeria</option>
<option value="US">United States</option>
<option value="GB">United Kingdom</option>
<option value="CA">Canada</option>
<option value="DE">Germany</option>
<option value="FR">France</option>
<option value="CN">China</option>
<option value="JP">Japan</option>
<option value="AU">Australia</option>
<option value="NZ">New Zealand</option>
<option value="SG">Singapore</option>
<option value="HK">Hong Kong</option>
<option value="TW">Taiwan</option>
<option value="KR">South Korea</option>
<option value="IN">India</option>
<option value="SA">Saudi Arabia</option>
<option value="AE">United Arab Emirates</option>
<option value="ZA">South Africa</option>
<option value="MX">Mexico</option>
<option value="CL">Chile</option>
<option value="AR">Argentina</option>
<option value="CO">Colombia</option>
<option value="PE">Peru</option>
<option value="VE">Venezuela</option>
<option value="UY">Uruguay</option>
<option value="PY">Paraguay</option>
<option value="CR">Costa Rica</option>
<option value="PA">Panama</option>
<option value="DO">Dominican Republic</option>
<option value="EC">Ecuador</option>
<option value="BO">Bolivia</option>
<option value="HN">Honduras</option>
<option value="NI">Nicaragua</option>
<option value="SV">El Salvador</option>
<option value="GT">Guatemala</option>
<option value="BS">Bahamas</option>
<option value="BZ">Belize</option>
<option value="JM">Jamaica</option>
<option value="TT">Trinidad and Tobago</option>
<option value="VC">Saint Vincent and the Grenadines</option>
